on:
  workflow_dispatch:
    inputs:
      which:
        type: choice
        description: Which dependents to check
        options:
        - strong
        - most

name: Run a recheck

jobs:
  revdep_check:
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: strong
