name: Run a recheck

on:
  push:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: ghcr.io/r-universe-org/recheck
    env:
      R_LIBS_USER: ${{github.workspace}}/pkglib
    steps:
      - name: clone
        run: git clone --depth=1 https://github.com/${{github.repository}} source

      - name: download dependencies
        run: recheck::install_recheck_deps('source')
        shell: Rscript {0}

      - name: build source package
        run: |
          mkdir checkdir
          R CMD build source
          mv *.tar.gz checkdir/

      - name: Save package and library
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/pkglib
            checkdir
          key: ${{ runner.os }}-${{ github.run_id }}-${{github.run_attempt}}

  checks:
    runs-on: ubuntu-latest
    container: ghcr.io/r-universe-org/recheck
    strategy:
      matrix:
        check: [ 'old', 'new' ]
    env:
      R_LIBS_USER: ${{github.workspace}}/pkglib
    steps:
      - name: Download
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-${{ github.run_id }}-${{github.run_attempt}}


